In [60]:
#def add(a,b):
   # return a+b
#add(2,3)
#wrong
a=float(input()) # Take a Number
b=float(input()) # An other one 
ADD=lambda a,b:a+b #Add a and b Number Using lambda 
ADD(a,b)           # call lambda fun()


5
10


15.0

In [61]:
# Find the prime Number b/w 1 to 100
for num in range(1,101): # iterate the num b/w 1 to 100
    if num > 1:          # check the num
        for i in range(2,num): # remove even number from num 
            if (num % i )==0:  # Again check, num is divisble by remaining numbers .and remainder should be 0
                break
        else:
            print(num) #print the num

2
3
5
7
11
13
17
19
23
29
31
37
41
43
47
53
59
61
67
71
73
79
83
89
97


In [17]:
# find odd number b/w 1 to 100 using list compre..
B=[Num for Num in range(1,101) if Num % 2==1]
print(B)

[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99]


In [63]:
# Take the random number & find the mean, median, cumulative sum 
import numpy as np # import numpy
random_numbers=np.random.random(20) #take a varialble & random number 
print(random_numbers)

[ 0.52757521  0.21835131  0.88782821  0.96315972  0.71262536  0.33168848
  0.20696335  0.99376545  0.81467696  0.74599281  0.26469915  0.01916209
  0.21554059  0.06514628  0.42370856  0.46799994  0.34454473  0.70259033
  0.96838526  0.82590752]


In [64]:
mean_=np.mean(random_numbers) # mean
print(mean_)
median_=np.median(random_numbers) # median 
print(median_)
cum_sum=np.cumsum(random_numbers) # cumulative sum 
print(cum_sum)

0.535015564855
0.497787575899
[  0.52757521   0.74592652   1.63375473   2.59691445   3.30953981
   3.64122828   3.84819163   4.84195708   5.65663405   6.40262686
   6.66732601   6.6864881    6.90202869   6.96717497   7.39088353
   7.85888347   8.20342819   8.90601852   9.87440377  10.7003113 ]


In [65]:
# Take two array of 3*3 & and add two arrays element
Array_1=np.arange(0,9).reshape(3,3) # it's first array of 3*3
print("it's First array :\n",Array_1) # print(array)
Array_2=np.arange(10,19).reshape(3,3) # it's second array 
print("it's Second array :\n",Array_2) # print(array)

it's First array :
 [[0 1 2]
 [3 4 5]
 [6 7 8]]
it's Second array :
 [[10 11 12]
 [13 14 15]
 [16 17 18]]


In [66]:
Array_3=Array_1+Array_2 # ADD first and second array in new_variable/new_array 
print(Array_3) #print(new array)

[[10 12 14]
 [16 18 20]
 [22 24 26]]


In [1]:
#print the triangle pattern   
#    1
#    2 2 
#    3 3 3
#    4 4 4 4
#    5 5 5 5 
#    and so... on(1,9)
for i in range(1,10):
    for j in range(1,i+1):
        print(i,end=' ')
    print()

1 
2 2 
3 3 3 
4 4 4 4 
5 5 5 5 5 
6 6 6 6 6 6 
7 7 7 7 7 7 7 
8 8 8 8 8 8 8 8 
9 9 9 9 9 9 9 9 9 


In [2]:
# print the pattern 
#num=int(input("enter a number")) 
num=5 #take a triangle length
for i in range(1,num+1): # and iterate the number 1 ,till giving number
    for j in range(1,i+1): # and iterate again iterating number
        print("*",end=" ") # print a string "*" , default a newline.

    print()

* 
* * 
* * * 
* * * * 
* * * * * 


In [4]:
#num=int(input("enter a number"))
num=6
for i in range(num,0,-1):  # same as first
# But iterate number from last
    for j in range(1,i):
        print("*",end=" ")
    print()

* * * * * 
* * * * 
* * * 
* * 
* 



In [73]:
for i in range(0,10):
    for j in range(0,i+1):
        print(j,end=' ')
    print()

0 
0 1 
0 1 2 
0 1 2 3 
0 1 2 3 4 
0 1 2 3 4 5 
0 1 2 3 4 5 6 
0 1 2 3 4 5 6 7 
0 1 2 3 4 5 6 7 8 
0 1 2 3 4 5 6 7 8 9 


In [74]:
import itertools
def count(n):
    for i in range(n,0,-1):
        print(i)
    print("Done")
count(10)

10
9
8
7
6
5
4
3
2
1
Done


In [75]:
li=[1,1,0,3,5,7,7]
k=list(set(li))
print(k)


[0, 1, 3, 5, 7]


In [76]:
li1=[1,2,3,4,5]
li2=[5,6,7,8,9]
[sum(x) for x in zip(li1, li2)]


[6, 8, 10, 12, 14]

In [77]:
li=[1,1,0,3,5,7,7]
new_li=[]
for i in li:
    if i not in new_li:
        new_li.append(i)
print(new_li)


[1, 0, 3, 5, 7]


In [78]:
s="How are you & How is your day"
len(s)

29